apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhs-crawer1
  labels:
    app: crawer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawer1
  template:
    metadata:
      labels:
        app: crawer1
    spec:
      containers:
      - name: crawer1
        image: royjian/bike-hot-spot
        command: ['sh', '-c', 'ts-node services/Crawer1.ts']
        envFrom:
          - configMapRef:
              name: nodejs-config
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
      initContainers:
      - name: init-rabbitmq
        image: busybox:1.31
        command: ['sh', '-c', 'until nc -zv $RABBITMQ_HOST $RABBITMQ_PORT; do echo waiting for myservice; sleep 2; done']
        envFrom:
          - configMapRef:
              name: nodejs-config
      - name: init-mongodb
        image: busybox:1.31
        command: ['sh', '-c', "until  nc -zv $MONGODB_HOST $MONGODB_PORT; do echo waiting for mydb; sleep 2; done"]
        envFrom:
          - configMapRef:
              name: nodejs-config