apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhs-crawer2
  labels:
    app: crawer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawer2
  template:
    metadata:
      labels:
        app: crawer2
    spec:
      containers:
      - name: crawer2
        image: royjian/bike-hot-spot
        command: ['sh', '-c', 'ts-node services/Crawer2.ts']
        envFrom:
          - configMapRef:
              name: nodejs-config
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
      initContainers:
      - name: init-rabbitmq
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup $RABBITMQ_HOST; do echo waiting for myservice; sleep 2; done']
        envFrom:
          - configMapRef:
              name: nodejs-config
      - name: init-mongodb
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup $MONGODB_HOST; do echo waiting for mydb; sleep 2; done"]
        envFrom:
          - configMapRef:
              name: nodejs-config