apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  PORT : 4000
  RABBITMQ_HOST : bhs-rabbitmq
  RABBITMQ_PORT : 5672
  MONGODB_HOST : bhs-mongodb
  MONGODB_PORT : 27017
  MONGODB_USER : root
  MONGODB_PASS : admin
  MONGODB_DB : BikeHotSpot